In [1]:
import numpy as np
import cv2
import sys
import time

In [2]:
cv2.namedWindow("tracking")
camera = cv2.VideoCapture("../1_021.avi")
tracker = cv2.MultiTracker_create()
init_once = False
ok, image = camera.read()
if not ok:
    print("Failed to read video")
    exit()
font = cv2.FONT_HERSHEY_COMPLEX
bbox1 = cv2.selectROI('tracking', image)
bbox2 = cv2.selectROI('tracking', image)
bbox3 = cv2.selectROI('tracking', image)
print(type(bbox1))
print(bbox1)
num_frame = 0
start = time.time()
while True:
    ok, image = camera.read()
    if not ok:
        print("No image to read")
        break
    
    if not init_once:
        ok = tracker.add(cv2.TrackerMedianFlow_create(), image, bbox1)
        ok = tracker.add(cv2.TrackerMedianFlow_create(), image, bbox2)
        ok = tracker.add(cv2.TrackerMedianFlow_create(), image, bbox3)
        
        init_once = True
        
    ok, boxes = tracker.update(image)
    print(boxes)
    print(type(boxes))
    print(ok, boxes)
    
    for newbox in boxes:
        p1 = (int(newbox[0]), int(newbox[1]))
        p2 = (int(newbox[0] + newbox[2]), int(newbox[1] + newbox[3]))
        cv2.rectangle(image, p1, p2, (200, 0, 0))
    
    fps = float(num_frame) / (time.time() - start)
    cv2.putText(image, str(fps), (20, 20), font, 1, (0, 244, 0), 3)
    cv2.imshow("image", image)
    
    # Check for key strokes
    k = cv2.waitKey(1) & 0xff
    if k == ord('n'):
        continue
    elif k == 27:  # 'esc' key has been pressed, exit program.
        break
    num_frame += 1
cap.release()
cv2.destroyAllWindows()           


<class 'tuple'>
(406, 211, 76, 279)
[[406. 211.  76. 279.]
 [161. 149.  36. 110.]
 [264. 136.  61.  84.]]
<class 'numpy.ndarray'>
True [[406. 211.  76. 279.]
 [161. 149.  36. 110.]
 [264. 136.  61.  84.]]
[[415.41434526 213.59914362  75.680892   277.82853772]
 [161.00154016 149.00355062  36.00116162 110.00354939]
 [264.00871221 135.9925173   60.99383656  83.99151264]]
<class 'numpy.ndarray'>
True [[415.41434526 213.59914362  75.680892   277.82853772]
 [161.00154016 149.00355062  36.00116162 110.00354939]
 [264.00871221 135.9925173   60.99383656  83.99151264]]
[[424.16156912 215.1757607   75.75199604 278.08956442]
 [161.00505778 149.01998278  35.99412639 109.98205286]
 [264.02696367 136.01239918  60.9669772   83.95452598]]
<class 'numpy.ndarray'>
True [[424.16156912 215.1757607   75.75199604 278.08956442]
 [161.00505778 149.01998278  35.99412639 109.98205286]
 [264.02696367 136.01239918  60.9669772   83.95452598]]
[[428.48417682 217.22952558  74.83584558 274.72632787]
 [161.00240773 149

[[445.90929823 220.96304873  76.17829075 279.65451473]
 [160.99476474 149.02809705  36.01117242 110.03413794]
 [264.02976271 136.00527015  60.96974093  83.95833178]]
<class 'numpy.ndarray'>
False [[445.90929823 220.96304873  76.17829075 279.65451473]
 [160.99476474 149.02809705  36.01117242 110.03413794]
 [264.02976271 136.00527015  60.96974093  83.95833178]]
[[187.06953077 -76.93616697  76.17829075 279.65451473]
 [161.00150995 149.05000693  36.00033704 110.00102984]
 [264.0197328  135.99480815  60.98012668  83.97263346]]
<class 'numpy.ndarray'>
True [[187.06953077 -76.93616697  76.17829075 279.65451473]
 [161.00150995 149.05000693  36.00033704 110.00102984]
 [264.0197328  135.99480815  60.98012668  83.97263346]]
[[187.06623857 -76.92524697  76.17297329 279.63499407]
 [161.00211905 149.05946357  35.99649432 109.98928819]
 [264.03703091 136.00901296  60.95541816  83.93860861]]
<class 'numpy.ndarray'>
True [[187.06623857 -76.92524697  76.17297329 279.63499407]
 [161.00211905 149.05946357

[[187.17674884 -76.80764427  76.10562403 279.38775138]
 [160.98026225 149.0978624   36.00076395 110.00233428]
 [263.73898279 136.10558769  61.09936597  84.13683182]]
<class 'numpy.ndarray'>
True [[187.17674884 -76.80764427  76.10562403 279.38775138]
 [160.98026225 149.0978624   36.00076395 110.00233428]
 [263.73898279 136.10558769  61.09936597  84.13683182]]
[[187.17285169 -76.81469754  76.10949681 279.40196856]
 [160.97329756 149.08975906  36.00804049 110.02456818]
 [263.710746   136.11011499  61.0911728   84.12554943]]
<class 'numpy.ndarray'>
True [[187.17285169 -76.81469754  76.10949681 279.40196856]
 [160.97329756 149.08975906  36.00804049 110.02456818]
 [263.710746   136.11011499  61.0911728   84.12554943]]
[[187.1794233  -76.78566311  76.09278304 279.34061142]
 [160.97173461 149.08922658  36.00919802 110.02810507]
 [263.58355427 136.06483103  61.14670371  84.20201823]]
<class 'numpy.ndarray'>
True [[187.1794233  -76.78566311  76.09278304 279.34061142]
 [160.97173461 149.08922658 

[[187.16881282 -76.79130313  76.09425912 279.34603018]
 [160.98390426 149.10785736  35.99775239 109.99313232]
 [263.78980994 136.24691839  61.01950122  84.02685414]]
<class 'numpy.ndarray'>
True [[187.16881282 -76.79130313  76.09425912 279.34603018]
 [160.98390426 149.10785736  35.99775239 109.99313232]
 [263.78980994 136.24691839  61.01950122  84.02685414]]
[[187.17014109 -76.78712012  76.09180095 279.33700613]
 [160.98287893 149.10706918  35.99916218 109.99744001]
 [263.80338306 136.25393327  61.0064541   84.00888761]]
<class 'numpy.ndarray'>
True [[187.17014109 -76.78712012  76.09180095 279.33700613]
 [160.98287893 149.10706918  35.99916218 109.99744001]
 [263.80338306 136.25393327  61.0064541   84.00888761]]
[[187.17006784 -76.78122007  76.09109297 279.33440707]
 [160.98168304 149.1062176   35.99953981 109.99859385]
 [263.78340634 136.23104526  61.04140264  84.05701348]]
<class 'numpy.ndarray'>
True [[187.17006784 -76.78122007  76.09109297 279.33440707]
 [160.98168304 149.1062176  

[[187.22887474 -76.79313885  76.0900563  279.33060142]
 [160.97090684 149.13948209  36.00436858 110.01334844]
 [263.93206453 136.14431352  60.8989935   83.86090909]]
<class 'numpy.ndarray'>
True [[187.22887474 -76.79313885  76.0900563  279.33060142]
 [160.97090684 149.13948209  36.00436858 110.01334844]
 [263.93206453 136.14431352  60.8989935   83.86090909]]
[[187.22887474 -76.79313885  76.0900563  279.33060142]
 [160.97175383 149.14103763  36.00386477 110.01180902]
 [263.8993749  136.105722    60.95344746  83.93589487]]
<class 'numpy.ndarray'>
True [[187.22887474 -76.79313885  76.0900563  279.33060142]
 [160.97175383 149.14103763  36.00386477 110.01180902]
 [263.8993749  136.105722    60.95344746  83.93589487]]
[[187.22900678 -76.79265414  76.08979223 279.32963201]
 [160.96841007 149.13507311  36.00605096 110.01848904]
 [263.90496551 136.09158271  60.95960024  83.94436754]]
<class 'numpy.ndarray'>
True [[187.22900678 -76.79265414  76.08979223 279.32963201]
 [160.96841007 149.13507311 

[[187.25697992 -76.80233069  76.08304028 279.30484524]
 [109.80286977 149.94512645  40.83882528 124.78529948]
 [246.24568815 134.28178047  66.44041691  91.49172165]]
<class 'numpy.ndarray'>
True [[187.25697992 -76.80233069  76.08304028 279.30484524]
 [109.80286977 149.94512645  40.83882528 124.78529948]
 [246.24568815 134.28178047  66.44041691  91.49172165]]
[[187.25998069 -76.7924818   76.07752702 279.28460578]
 [100.91274477 149.57794742  41.54552028 126.94464531]
 [246.233473   134.26659555  66.46167339  91.52099286]]
<class 'numpy.ndarray'>
True [[187.25998069 -76.7924818   76.07752702 279.28460578]
 [100.91274477 149.57794742  41.54552028 126.94464531]
 [246.233473   134.26659555  66.46167339  91.52099286]]
[[187.25817014 -76.79907454  76.0800495  279.29386593]
 [ 91.83729803 149.9100863   42.31003835 129.28067273]
 [246.22979974 134.26028632  66.46505262  91.52564623]]
<class 'numpy.ndarray'>
True [[187.25817014 -76.79907454  76.0800495  279.29386593]
 [ 91.83729803 149.9100863  

[[187.22545603 -76.86553124  76.11718792 279.43020303]
 [ 16.67649053 161.55427422  47.58585789 145.40123245]
 [246.23119743 134.22557979  66.5279921   91.61231699]]
<class 'numpy.ndarray'>
True [[187.22545603 -76.86553124  76.11718792 279.43020303]
 [ 16.67649053 161.55427422  47.58585789 145.40123245]
 [246.23119743 134.22557979  66.5279921   91.61231699]]
[[187.22752096 -76.86584456  76.11650654 279.42770162]
 [ 16.67530485 161.55065131  47.58822925 145.40847827]
 [246.2328797  134.23262732  66.51644886  91.59642138]]
<class 'numpy.ndarray'>
True [[187.22752096 -76.86584456  76.11650654 279.42770162]
 [ 16.67530485 161.55065131  47.58822925 145.40847827]
 [246.2328797  134.23262732  66.51644886  91.59642138]]
[[187.22748333 -76.86598272  76.11658181 279.42797794]
 [ 16.67494178 161.54935882  47.5889554  145.41069704]
 [246.23643406 134.23522441  66.51217827  91.59054057]]
<class 'numpy.ndarray'>
True [[187.22748333 -76.86598272  76.11658181 279.42797794]
 [ 16.67494178 161.54935882 

[[187.21429976 -76.89087162  76.1258591  279.46203537]
 [ 16.67530542 161.53911363  47.59402837 145.42619779]
 [246.26255494 134.2593537   66.46701658  91.5283507 ]]
<class 'numpy.ndarray'>
True [[187.21429976 -76.89087162  76.1258591  279.46203537]
 [ 16.67530542 161.53911363  47.59402837 145.42619779]
 [246.26255494 134.2593537   66.46701658  91.5283507 ]]
[[187.21395375 -76.89214185  76.12655112 279.46457583]
 [ 16.67568691 161.54136245  47.59231172 145.42095247]
 [246.2650007  134.26498043  66.46163678  91.52094246]]
<class 'numpy.ndarray'>
True [[187.21395375 -76.89214185  76.12655112 279.46457583]
 [ 16.67568691 161.54136245  47.59231172 145.42095247]
 [246.2650007  134.26498043  66.46163678  91.52094246]]
[[187.21400832 -76.89196432  76.12639621 279.46400714]
 [ 16.67622858 161.54192263  47.59157551 145.41870295]
 [246.26396053 134.26354807  66.46371712  91.52380719]]
<class 'numpy.ndarray'>
True [[187.21400832 -76.89196432  76.12639621 279.46400714]
 [ 16.67622858 161.54192263 

[[187.21619142 -76.92867338  76.1563165  279.57384608]
 [ 16.66087639 161.52651616  47.62069106 145.50766714]
 [246.21832442 134.10042676  66.7450986   91.91128331]]
<class 'numpy.ndarray'>
True [[187.21619142 -76.92867338  76.1563165  279.57384608]
 [ 16.66087639 161.52651616  47.62069106 145.50766714]
 [246.21832442 134.10042676  66.7450986   91.91128331]]
[[187.21393518 -76.93695617  76.16082899 279.59041168]
 [ 16.65947606 161.52331078  47.62288901 145.51438308]
 [246.22615303 134.09516579  66.74860641  91.91611374]]
<class 'numpy.ndarray'>
True [[187.21393518 -76.93695617  76.16082899 279.59041168]
 [ 16.65947606 161.52331078  47.62288901 145.51438308]
 [246.22615303 134.09516579  66.74860641  91.91611374]]
[[187.21400638 -76.93545802  76.16032037 279.58854452]
 [ 16.65793095 161.52166554  47.62428549 145.51865012]
 [246.2155981  134.08164746  66.76999093  91.94556128]]
<class 'numpy.ndarray'>
True [[187.21400638 -76.93545802  76.16032037 279.58854452]
 [ 16.65793095 161.52166554 

KeyboardInterrupt: 

In [ ]:

import numpy as np
import cv2 as cv
import sys

if len(sys.argv) != 2:
    print('Input video name is missing')
    exit()

cv.namedWindow("tracking")
camera = cv.VideoCapture(0)
ok, image=camera.read()
if not ok:
    print('Failed to read video')
    exit()
bbox = cv.selectROI("tracking", image)
tracker = cv.TrackerMIL_create()
init_once = False

while camera.isOpened():
    ok, image=camera.read()
    if not ok:
        print ('no image to read')
        break

    if not init_once:
        ok = tracker.init(image, bbox)
        init_once = True

    ok, newbox = tracker.update(image)
    print (ok, newbox)

    if ok:
        p1 = (int(newbox[0]), int(newbox[1]))
        p2 = (int(newbox[0] + newbox[2]), int(newbox[1] + newbox[3]))
        cv.rectangle(image, p1, p2, (200,0,0))

    cv.imshow("tracking", image)
    k = cv.waitKey(1) & 0xff
    if k == 27 : break # esc pressed